>P1;Alpha-1

----TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-----------------------------------KIDRLSRIAF
PLLFGIFNLVYWATYL---
*
>P1;Alpha-2

----TIFTRILDRLLDGYDNRLRPGLGDSITEVFTNIYVTSFGPVSDTDMEYTIDVFFRQ
KWKDERLKF-KGPMNILRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRIQDDGTL
LYTMRLTVQAECPMHLEDFPMDAHSCPLKFGSYAYTTSEVTYIWTYNASDSVQV----AP
DGS----RLNQYDLLGQSIGKETIKSST-GEYTVMTAHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-----------------------------------KIDRMSRIVF
PVLFGTFNLVYWATYL---
*
>P1;Alpha-3

----TIFTRILDRLLDGYDNRLRPGLGDAVTE-KTDIYVTSFGPVSDTDMEYTIDVFFRQ
TWHDERLKF-DGPMKILPLNNLLASKIWTPDTFFHNGKKSVAHNMTTPNKLLRLVDNGTL
LYTMRLTIHAECPMHLEDFPMDVHACPLKFGSYAYTTAEVVYSWTLGKNKSVEV----AQ
DGS----RLNQYDLLGHVVGTEIIRSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-----------------------------------KVDKISRIIF
PVLFAIFNLVYWATYV---
*
>P1;Alpha-5

----TIFTRILDGLLDGYDNRLRPGLGERITQVRTDIYVTSFGPVSDTEMEYTIDVFFRQ
SWKDERLRF-KGPMQRLPLNNLLASKIWTPDTFFHNGKKSIAHNMTTPNKLLRLEDDGTL
LYTMRLTISAECPMQLEDFPMDAHACPLKFGSYAYPNSEVVYVWTNGSTKSVVV----AE
DGS----RLNQYHLMGQTVGTENISTST-GEYTIMTAHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-----------------------------------KIDKMSRIVF
PVLFGTFNLVYWATYL---
*
>P1;Alpha-4

----ENFTRILDSLLDGYDNRLRPGFGGPVTEVKTDIYVTSFGPVSDVEMEYTMDVFFRQ
TWIDKRLKY-DGPIEILRLNNMMVTKVWTPDTFFRNGKKSVSHNMTAPNKLFRIMRNGTI
LYTMRLTISAECPMRLVDFPMDGHACPLKFGSYAYPKSEMIYTWTKGPEKSVEV----PK
ESS----SLVQYDLIGQTVSSETIKSIT-GEYIVMTVYFHLRRKMGYFMIQTYIPCIMTV
ILSQVSFWINKESVPARTVFGITTVLTMTTLSISARHSLPKVSY-ATAMDWFIAVCFAFV
FSALIEFAAVNYFTN-----------------------------------KIDKYARILF
PVTFGAFNMVYWVVYL---
*
>P1;Alpha-6

----ENVSRILDNLLEGYDNRLRPGFGGAVTEVKTDIYVTSFGPVSDVEMEYTMDVFFRQ
TWTDERLKF-GGPTEILSLNNLMVSKIWTPDTFFRNGKKSIAHNMTTPNKLFRIMQNGTI
LYTMRLTINADCPMRLVNFPMDGHACPLKFGSYAYPKSEIIYTWKKGPLYSVEV----PE
ESS----SLLQYDLIGQTVSSETIKSNT-GEYVIMTVYFHLQRKMGYFMIQIYTPCIMTV
ILSQVSFWINKESVPARTVFGITTVLTMTTLSISARHSLPKVSY-ATAMDWFIAVCFAFV
FSALIEFAAVNYFTN-----------------------------------KIDQYSRILF
PVAFAGFNLVYWVVYL---
*
>P1;Gamma-1

----GDITQILNSLLQGYDNKLRPDIGVRPTVIETDVYVNSIGPVDPINMEYTIDIIFAQ
TWFDSRLKF-NSTMKVLMLNSNMVGKIWIPDTFFRNSRKSDAHWITTPNRLLRIWNDGRV
LYTLRLTINAECYLQLHNFPMDEHSCPLEFSSYGYPKNEIEYKWKK---PSVEV----AD
---PKYWRLYQFAFVGLRNSTEITHTIS-GDYVIMTIFFDLSRRMGYFTIQTYIPCILTV
VLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFV
FAALMEYGTLHYFTS-----------------------------------KIDSYSRIFF
PTAFALFNLVYWVGYL---
*
>P1;Gamma-2

----GDVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQ
TWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRV
LYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD
---TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIV
VLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFV
FSALVEYGTLHYFVS-----------------------------------KMDSYARIFF
PTAFCLFNLVYWVSYL---
*
>P1;Gamma-3

----TDVTLILNKLLREYDKKLRPDIGIKPTVIDVDIYVNSIGPVSSINMEYQIDIFFAQ
TWTDSRLRF-NSTMKILTLNSNMVGLIWIPDTIFRNSKTAEAHWITTPNQLLRIWNDGKI
LYTLRLTINAECQLQLHNFPMDEHSCPLIFSSYGYPKEEMIYRWRK---NSVEA----AD
---QKSWRLYQFDFMGLRNTTEIVTTSA-GDYVVMTIYFELSRRMGYFTIQTYIPCILTV
VLSWVSFWIKKDATPARTALGITTVLTMTTLSTIARKSLPRVSY-VTAMDLFVTVCFLFV
FAALMEYATLNYYSS-----------------------------------ELDSYSRVFF
PTSFLLFNLVYWVGYL---
*
>P1;Beta-1

----SYVKETVDRLLKGYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTMYFQQ
SWKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG-GEGAVTGVNKI--
-------ELPQFSIVDYKMVSKKVEFTT-GAYPRLSLSFRLKRNIGYFILQTYMPSTLIT
ILSWVSFWINYDASAARVALGITTVLTMTTISTHLRETLPKIPY-VKAIDIYLMGCFVFV
FLALLEYAFVNYIFF-----------------------------------SIDKWSRMFF
PITFSLFNVVYWLYYV---
*
>P1;Beta-2

----SLVKETVDRLLKGYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTMYFQQ
AWRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-DDNAVTGVTKI--
-------ELPQFSIVDYKLITKKVVFST-GSYPRLSLSFKLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FMALLEYALVNYIFF-----------------------------------AIDRWSRIFF
PVVFSFFNIVYWLYYV---
*
>P1;Beta-3

----SFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFF-----------------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;Epsilon

----PEASRILNTILSNYDHKLRPGIGEKPTVVTVEISVNSLGPLSILDMEYTIDIIFSQ
TWYDERLCY-NDTFESLVLNGNVVSQLWIPDTFFRNSKRTHEHEITMPNQMVRIYKDGKV
LYTIRMTIDAGCSLHMLRFPMDSHSCPLSFSSFSYPENEMIYKWEN-FKLEINEKNSW--
-------KLFQFDFTGVSNKTEIITTPV-GDFMVMTIFFNVSRRFGYVAFQNYVPSSVTT
MLSWVSFWIKTESAPARTSLGITSVLTMTTLGTFSRKNFPRVSY-ITALDFYIAICFVFC
FCALLEFAVLNFLIY-----------------------------------RLDNYSRVVF
PVTFFFFNVLYWLVCL---
*
>P1;Delta

----ISWLPNLDGLIAGYARNFRPGIGGPPVNVALALEVASIDHISEANMEYTMTVFLHQ
SWRDSRLSY-NHTNETLGLDSRFVDKLWLPDTFIVNAKSAWFHDVTVENKLIRLQPDGVI
LYSIRITSTVACDMDLAKYPMDEQECMLDLESYGYSSEDIVYYWSESQEH-IHGLDKL--
-------QLAQFTITSYRFTTELMNFKSAGQFPRLSLHFHLRRNRGVYIIQSYMPSVLLV
AMSWVSFWISQAAVPARVSLGITTVLTMTTLMVSARSSLPRASA-IKALDVYFWICYVFV
FAALVEYAFAHFNAD-----------------------------------TIDIYARAVF
PAAFAAVNVIYWAAYA---
*
>P1;Theta

----AVVQKILDRVLSRYDVRLRPNFGGAPVPVRISIYVTSIEQISEMNMDYTITMFFHQ
TWKDSRLAY-YETTLNLTLDYRMHEKLWVPDCYFLNSKDAFVHDVTVENRVFQLHPDGTV
RYGIRLTTTAACSLDLHKFPMDKQACNLVVESYGYTVEDIILFWDDNG-NAIHMTEEL--
-------HIPQFTFLGRTITSKEVYFYT-GSYIRLILKFQVQREVNSYLVQVYWPTVLTT
ITSWISFWMNYDSSAARVTIGLTSMLILTTIDSHLRDKLPNISC-IKAIDIYILVCLFFV
FLSLLEYVYINYLFY-----------------------------------KVDKWSRFLF
PLAFGLFNIVYWVYHM---
*
>P1;Pi

----KLSLPGFENLTAGYNKFLRPNFGGEPVQIALTLDIASISSISESNMDYTATIYLRQ
RWMDQRLVF-EGNK-SFTLDARLVEFLWVPDTYIVESKKSFLHEVTVGNRLIRLFSNGTV
LYALRITTTVACNMDLSKYPMDTQTCKLQLESWGYDGNDVEFTWLR-GNDSVRGLEHL--
-------RLAQYTIERYFTLVTRSQQET-GNYTRLVLQFELRRNVLYFILETYVPSTFLV
VLSWVSFWISLDSVPARTCIGVTTVLSMTTLMIGSRTSLPNTNCFIKAIDVYLGICFSFV
FGALLEYAVAHYSSL-----------------------------------NVDHYSKLLF
PLIFMLANVFYWAYYM---
*
>P1;Rho-1

-----LTKSEQLLRIDDHDFSMRPGFGGPAIPVGVDVQVESLDSISEVDMDFTMTLYLRH
YWKDERLSFPSTNNLSMTFDGRLVKKIWVPDMFFVHSKRSFIHDTTTDNVMLRVQPDGKV
LYSLRVTVTAMCNMDFSRFPLDTQTCSLEIESYAYTEDDLMLYWKK-GNDSLKTDERI--
-------SLSQFLIQEFHTTTKLAFYSSTGWYNRLYINFTLRRHIFFFLLQTYFPATLMV
MLSWVSFWIDRRAVPARVPLGITTVLTMSTIITGVNASMPRVSY-IKAVDIYLWVSFVFV
FLSVLEYAAVNYLTT-----------------------------------AIDKYSRIIF
PAAYILFNLIYWSIFS---
*
>P1;Rho-2

-TKIRKGKPQQLLRVDEHDFSMRPAFGGPAIPVGVDVQVESLDSISEVDMDFTMTLYLRH
YWKDERLAFSSASNKSMTFDGRLVKKIWVPDVFFVHSKRSFTHDTTTDNIMLRVFPDGHV
LYSMRITVTAMCNMDFSHFPLDSQTCSLELESYAYTDEDLMLYWKN-GDESLKTDEKI--
-------SLSQFLIQKFHTTSRLAFYSSTGWYNRLYINFTLRRHIFFFLLQTYFPATLMV
MLSWVSFWIDRRAVPARVSLGITTVLTMTTIITGVNASMPRVSY-VKAVDIYLWVSFVFV
FLSVLEYAAVNYLTT-----------------------------------AIDKYSRLIF
PASYIFFNLIYWSVFS---
*
>P1;Rho-3

-----PQKYEQLLHIEDNDFAMRPGFGGSPVPVGIDVHVESIDSISETNMDFTMTFYLRH
YWKDERLSFPSTANKSMTFDHRLTRKIWVPDIFFVHSKRSFIHDTTMENIMLRVHPDGNV
LLSLRITVSAMCFMDFSRFPLDTQNCSLELESYAYNEDDLMLYWKH-GNKSLNTEEHM--
-------SLSQFFIEDFSASSGLAFYSSTGWYNRLFINFVLRRHVFFFVLQTYFPAILMV
MLSWVSFWIDRRAVPARVSLGITTVLTMSTIITAVSASMPQVSY-LKAVDVYLWVSSLFV
FLSVIEYAAVNYLTT-----------------------------------VIDTYSRILF
PIVYILFNLFYWGVYV---
*
>P1;4COF.A_b3
TRANSPORT PROTEIN
----SFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFSQPARAA----------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;4COF.B_b3
TRANSPORT PROTEIN
----SFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFSQPARAA----------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;4COF.C_b3
TRANSPORT PROTEIN
----SFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFSQPARAA----------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;4COF.D_b3
TRANSPORT PROTEIN
----SFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFSQPARAA----------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYVN--
*
>P1;4COF.E_b3
TRANSPORT PROTEIN
----SFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFSQPARAA----------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6D6T.B_a1
TRANSPORT PROTEIN
----TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDRLSRIAF
PLLFGIFNLVYWATYL---
*
>P1;6D6T.D_a1
TRANSPORT PROTEIN
--NTTVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6D6T.A_b2
TRANSPORT PROTEIN
--NMSLVKETVDRLLKGYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTMYFQQ
AWRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-DDNAVTGVTKI--
-------ELPQFSIVDYKLITKKVVFST-GSYPRLSLSFKLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FMALLEYALVNYIFFSQPARAA----------------------------AIDRWSRIFF
PVVFSFFNIVYWLYYV---
*
>P1;6D6T.C_b2
TRANSPORT PROTEIN
--NMSLVKETVDRLLKGYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTMYFQQ
AWRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-DDNAVTGVTKI--
-------ELPQFSIVDYKLITKKVVFST-GSYPRLSLSFKLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FMALLEYALVNYIFFSQPARAA----------------------------AIDRWSRIFF
PVVFSFFNIVYWLYYV---
*
>P1;6D6T.E_g2
TRANSPORT PROTEIN
----GDVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQ
TWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRV
LYTLRLTIDAECQLQLHN---DEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD
---TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIV
VLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSL---------------------
------------------------------------------------------------
-------------------
*
>P1;6HUG.A_a1
MEMBRANE PROTEIN
-DNTTVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-------RGYAWDGKS--KTFNSVS----------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUG.D_a1
MEMBRANE PROTEIN
KDNTTVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-------RGYAWDGK---KTFNSVS----------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUG.B_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFGRGPQR----------------------TDVN---AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUG.E_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFGRGPQ------------------------DVN---AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUG.C_g2
MEMBRANE PROTEIN
-----DVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQ
TWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRV
LYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD
---TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIV
VLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFV
FSALVEYGTLHYFVSNR------------------------------RIAKMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
>P1;6HUJ.A_a1
MEMBRANE PROTEIN
-DNTTVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-------RGYAWDGKS--KTFNSVS----------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUJ.D_a1
MEMBRANE PROTEIN
---TTVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-------RGYAWDGK---KTFNSVS----------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUJ.B_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFGRGPQR----------------------TDVN---AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUJ.E_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFGRGPQ------------------------DVN---AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUJ.C_g2
MEMBRANE PROTEIN
-----DVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQ
TWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRV
LYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD
---TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIV
VLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFV
FSALVEYGTLHYFVSNR------------------------------RIAKMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
>P1;6HUK.A_a1
MEMBRANE PROTEIN
-DNTTVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-------RGYAWDGKS--KTFNSVS----------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUK.D_a1
MEMBRANE PROTEIN
KDNTTVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-------RGYAWDGK---KTFNSVS----------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUK.B_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFGRGPQR----------------------TDVN---AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUK.E_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFGRGPQ------------------------DVN---AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUK.C_g2
MEMBRANE PROTEIN
-----DVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQ
TWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRV
LYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD
---TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIV
VLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFV
FSALVEYGTLHYFVSNR------------------------------RIAKMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
>P1;6HUO.A_a1
MEMBRANE PROTEIN
----TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-------RGYAWDGKS--KTFNSVS----------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUO.D_a1
MEMBRANE PROTEIN
----TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-------RGYAWDGKS--KTFNSVS----------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUO.B_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFGRGPQR----------------------TDVN---AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUO.E_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFGRGPQ------------------------DVN---AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUO.C_g2
MEMBRANE PROTEIN
-----DVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQ
TWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRV
LYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD
---TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIV
VLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFV
FSALVEYGTLHYFVSNR------------------------------RIAKMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
>P1;6HUP.A_a1
MEMBRANE PROTEIN
----TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-------RGYAWDGKS--KTFNSVS----------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUP.D_a1
MEMBRANE PROTEIN
----TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-------RGYAWDGK---KTFNSVS----------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUP.B_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFGRGPQR----------------------TDVN---AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUP.E_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFGRGPQ------------------------DVN---AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUP.C_g2
MEMBRANE PROTEIN
-----DVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQ
TWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRV
LYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD
---TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIV
VLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFV
FSALVEYGTLHYFVSNR------------------------------RIAKMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
>P1;6I53.A_a1
TRANSPORT PROTEIN
-DNTTVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-------RGYAWDGKSVVKTFNSVS----------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6I53.D_a1
TRANSPORT PROTEIN
-DNTTVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTK-------RGYAWDGKSV-KTFNSVS----------KIDRLSRIAF
PLLFGIFNLVYWATYLN--
*
>P1;6I53.B_b3
TRANSPORT PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFGRGPQ--------------------PDLTDVN---AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6I53.E_b3
TRANSPORT PROTEIN
----SFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFGRGPQ--------------------PDLTDVN---AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6I53.C_g2
TRANSPORT PROTEIN
------VTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQ
TWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRV
LYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD
---TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIV
VLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFV
FSALVEYGTLHYFVSN-------------------------------RIAKMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
>P1;5O8F.A_a5/b3
MEMBRANE PROTEIN
---MSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDKMSRIVF
PILFGTFNLVYWATYL---
*
>P1;5O8F.B_a5/b3
MEMBRANE PROTEIN
---MSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDKMSRIVF
PILFGTFNLVYWATYL---
*
>P1;5O8F.C_a5/b3
MEMBRANE PROTEIN
---MSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDKMSRIVF
PILFGTFNLVYWATYL---
*
>P1;5O8F.D_a5/b3
MEMBRANE PROTEIN
---MSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDKMSRIVF
PILFGTFNLVYWATYL---
*
>P1;5O8F.E_a5/b3
MEMBRANE PROTEIN
---MSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDKMSRIVF
PILFGTFNLVYWATYL---
*
>P1;5OJM.A_a5/b3
MEMBRANE PROTEIN
-----FVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDKMSRIVF
PILFGTFNLVYWATYL---
*
>P1;5OJM.B_a5/b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDKMSRIVF
PILFGTFNLVYWATYL---
*
>P1;5OJM.C_a5/b3
MEMBRANE PROTEIN
-----FVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDKMSRIVF
PILFGTFNLVYWATYL---
*
>P1;5OJM.D_a5/b3
MEMBRANE PROTEIN
---MSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDKMSRIVF
PILFGTFNLVYWATYL---
*
>P1;5OJM.E_a5/b3
MEMBRANE PROTEIN
-----FVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDKMSRIVF
PILFGTFNLVYWATYL---
*
>P1;6A96.A_a5
MEMBRANE PROTEIN
--NITIFTRILDGLLDGYDNRLRPGLGERITQVRTDIYVTSFGPVSDTEMEYTIDVFFRQ
SWKDERLRF-KGPMQRLPLNNLLASKIWTPDTFFHNGKKSIAHNMTTPNKLLRLEDDGTL
LYTMRLTISAECPMQLEDFPMDAHACPLKFGSYAYPNSEVVYVWTNGSTKSVVV----AE
DGS----RLNQYHLMGQTVGTENISTST-GEYTIMTAHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDKMSRIVF
PVLFGTFNLVYWATYLNR-
*
>P1;6A96.B_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFSQPARAA----------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6A96.E_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFSQPARAA----------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6A96.C_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFSQPARAA----------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6A96.D_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQ
YWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI--
-------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FLALLEYAFVNYIFFSQPARAA----------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6D6U.A_b2
TRANSPORT PROTEIN
--NMSLVKETVDRLLKGYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTMYFQQ
AWRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-DDNAVTGVTKI--
-------ELPQFSIVDYKLITKKVVFST-GSYPRLSLSFKLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FMALLEYALVNYIFFSQPARAA----------------------------AIDRWSRIFF
PVVFSFFNIVYWLYYV---
*
>P1;6D6U.C_b2
TRANSPORT PROTEIN
--NMSLVKETVDRLLKGYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTMYFQQ
AWRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-DDNAVTGVTKI--
-------ELPQFSIVDYKLITKKVVFST-GSYPRLSLSFKLKRNIGYFILQTYMPSILIT
ILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFV
FMALLEYALVNYIFFSQPARAA----------------------------AIDRWSRIFF
PVVFSFFNIVYWLYYV---
*
>P1;6D6U.B_a1
TRANSPORT PROTEIN
-DNTTVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDRLSRIAF
PLLFGIFNLVYWATYL---
*
>P1;6D6U.D_a1
TRANSPORT PROTEIN
-DNTTVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVNYFTKSQPARAA----------------------------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6D6U.E_g2
TRANSPORT PROTEIN
----GDVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQ
TWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRV
LYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD
---TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRR----TIQTYIPCTLIV
VLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKS-----Y-VTAMDLFVSVCFIFV
FSALVEYGTLHYFVSSQPARAA----------------------------KMDSYARIFF
PTAFCLFNLVYWVSYL---
*
>P1;6DW0.A_a1
MEMBRANE PROTEIN
----TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVN-------------------------------------------------
-------------------
*
>P1;6DW0.C_a1
MEMBRANE PROTEIN
----TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTV
ILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFV
FSALIEFATVN-------------------------------------------------
-------------------
*
>P1;6DW0.B_b1
MEMBRANE PROTEIN
----SYVKETVDRLLKGYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTMYFQQ
SWKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG-GEGAVTGVNKI--
-------ELPQFSIVDYKMVSKKVEFTT-GAYPRLSLSFRLKRNIGYFILQTYMPSTLIT
ILSWVSFWINYDASAARVALGITTVLTMTTISTHLRETLPKIPY-VKAIDIYLMGCFVFV
FLALLEYAFV-----------------------------------------IDKWSRMFF
PITFSLFNVVYWLYYVH--
*
>P1;6DW0.E_b1
MEMBRANE PROTEIN
----SYVKETVDRLLKGYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTMYFQQ
SWKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG-GEGAVTGVNKI--
-------ELPQFSIVDYKMVSKKVEFTT-GAYPRLSLSFRLKRNIGYFILQTYMPSTLIT
ILSWVSFWINYDASAARVALGITTVLTMTTISTHLRETLPKIPY-VKAIDIYLMGCFVFV
FLALLEYAFV-----------------------------------------IDKWSRMFF
PITFSLFNVVYWLYYVH--
*
>P1;6DW0.D_g2
MEMBRANE PROTEIN
----GDVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQ
TWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRV
LYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD
---TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIV
VLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFV
FSALVEYGTLHYFVSN--------------------------------------------
-------------------
*
>P1;6DW1.A_a1
MEMBRANE PROTEIN
----TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRK----------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
*
>P1;6DW1.C_a1
MEMBRANE PROTEIN
----TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
SWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTL
LYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AE
DGS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRK----------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
*
>P1;6DW1.B_b1
MEMBRANE PROTEIN
--NMSYVKETVDRLLKGYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTMYFQQ
SWKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG-GEGAVTGVNKI--
-------ELPQFSIVDYKMVSKKVEFTT-GAYPRLSLSFRLKRN----------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
*
>P1;6DW1.E_b1
MEMBRANE PROTEIN
----SYVKETVDRLLKGYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTMYFQQ
SWKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTV
LYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG-GEGAVTGVNKI--
-------ELPQFSIVDYKMVSKKVEFTT-GAYPRLSLSFRLKRN----------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
*
>P1;6DW1.D_g2
MEMBRANE PROTEIN
----GDVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQ
TWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRV
LYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD
---TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRR----------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
*
