>P1;Alpha-1

----TVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK--------------------------------------
----KIDRLSRIAFPLLFGIFNLVYWATYL--
*
>P1;Alpha-2

----TIFTRILDRLLD----GYDNRLRPGLGDSITEVFTNIYVTSFGPVSDTDMEYTIDV
FFRQKWKDERLKF-KGPMNILRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRIQD
DGTLLYTMRLTVQAECPMHLEDFPMDAHSCPLKFGSYAYTTSEVTYIWTY-NASDSVQVA
PDGSR----------LNQYDLL-GQSIGKETIKSSTGEYTVMTAHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK--------------------------------------
----KIDRMSRIVFPVLFGTFNLVYWATYL--
*
>P1;Alpha-3

----TIFTRILDRLLD----GYDNRLRPGLGDAVTE-KTDIYVTSFGPVSDTDMEYTIDV
FFRQTWHDERLKF-DGPMKILPLNNLLASKIWTPDTFFHNGKKSVAHNMTTPNKLLRLVD
NGTLLYTMRLTIHAECPMHLEDFPMDVHACPLKFGSYAYTTAEVVYSWTL-GKNKSVEVA
QDGSR----------LNQYDLL-GHVVGTEIIRSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK--------------------------------------
----KVDKISRIIFPVLFAIFNLVYWATYV--
*
>P1;Alpha-5

----TIFTRILDGLLD----GYDNRLRPGLGERITQVRTDIYVTSFGPVSDTEMEYTIDV
FFRQSWKDERLRF-KGPMQRLPLNNLLASKIWTPDTFFHNGKKSIAHNMTTPNKLLRLED
DGTLLYTMRLTISAECPMQLEDFPMDAHACPLKFGSYAYPNSEVVYVWTN-GSTKSVVVA
EDGSR----------LNQYHLM-GQTVGTENISTSTGEYTIMTAHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK--------------------------------------
----KIDKMSRIVFPVLFGTFNLVYWATYL--
*
>P1;Alpha-4

----ENFTRILDSLLD----GYDNRLRPGFGGPVTEVKTDIYVTSFGPVSDVEMEYTMDV
FFRQTWIDKRLKY-DGPIEILRLNNMMVTKVWTPDTFFRNGKKSVSHNMTAPNKLFRIMR
NGTILYTMRLTISAECPMRLVDFPMDGHACPLKFGSYAYPKSEMIYTWTK-GPEKSVEVP
KESSS----------LVQYDLI-GQTVSSETIKSITGEYIVMTVYFHLRRKMGYFMIQTY
IPCIMTVILSQVSFWINKESVPARTVFGITTVLTMTTLSISARHSLPKVSY-ATAMDWFI
AVCFAFVFSALIEFAAVNYFTN--------------------------------------
----KIDKYARILFPVTFGAFNMVYWVVYL--
*
>P1;Alpha-6

----ENVSRILDNLLE----GYDNRLRPGFGGAVTEVKTDIYVTSFGPVSDVEMEYTMDV
FFRQTWTDERLKF-GGPTEILSLNNLMVSKIWTPDTFFRNGKKSIAHNMTTPNKLFRIMQ
NGTILYTMRLTINADCPMRLVNFPMDGHACPLKFGSYAYPKSEIIYTWKK-GPLYSVEVP
EESSS----------LLQYDLI-GQTVSSETIKSNTGEYVIMTVYFHLQRKMGYFMIQIY
TPCIMTVILSQVSFWINKESVPARTVFGITTVLTMTTLSISARHSLPKVSY-ATAMDWFI
AVCFAFVFSALIEFAAVNYFTN--------------------------------------
----KIDQYSRILFPVAFAGFNLVYWVVYL--
*
>P1;Gamma-1

----GDITQILNSLLQ----GYDNKLRPDIGVRPTVIETDVYVNSIGPVDPINMEYTIDI
IFAQTWFDSRLKF-NSTMKVLMLNSNMVGKIWIPDTFFRNSRKSDAHWITTPNRLLRIWN
DGRVLYTLRLTINAECYLQLHNFPMDEHSCPLEFSSYGYPKNEIEYKWKK----PSVEVA
D----PKYWR-----LYQFAFV-GLRNSTEITHTISGDYVIMTIFFDLSRRMGYFTIQTY
IPCILTVVLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFV
SVCFIFVFAALMEYGTLHYFTS--------------------------------------
----KIDSYSRIFFPTAFALFNLVYWVGYL--
*
>P1;Gamma-2

----GDVTVILNNLLE----GYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDI
FFAQTWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWN
DGRVLYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR----SSVEVG
D----TRSWR-----LYQFSFV-GLRNTTEVVKTTSGDYVVMSVYFDLSRRMGYFTIQTY
IPCTLIVVLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFV
SVCFIFVFSALVEYGTLHYFVS--------------------------------------
----KMDSYARIFFPTAFCLFNLVYWVSYL--
*
>P1;Gamma-3

----TDVTLILNKLLR----EYDKKLRPDIGIKPTVIDVDIYVNSIGPVSSINMEYQIDI
FFAQTWTDSRLRF-NSTMKILTLNSNMVGLIWIPDTIFRNSKTAEAHWITTPNQLLRIWN
DGKILYTLRLTINAECQLQLHNFPMDEHSCPLIFSSYGYPKEEMIYRWRK----NSVEAA
D----QKSWR-----LYQFDFM-GLRNTTEIVTTSAGDYVVMTIYFELSRRMGYFTIQTY
IPCILTVVLSWVSFWIKKDATPARTALGITTVLTMTTLSTIARKSLPRVSY-VTAMDLFV
TVCFLFVFAALMEYATLNYYSS--------------------------------------
----ELDSYSRVFFPTSFLLFNLVYWVGYL--
*
>P1;Beta-1

----SYVKETVDRLLK----GYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTM
YFQQSWKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG--GEGAVTG-
----------VNKIELPQFSIV-DYKMVSKKVEFTTGAYPRLSLSFRLKRNIGYFILQTY
MPSTLITILSWVSFWINYDASAARVALGITTVLTMTTISTHLRETLPKIPY-VKAIDIYL
MGCFVFVFLALLEYAFVNYIFF--------------------------------------
----SIDKWSRMFFPITFSLFNVVYWLYYV--
*
>P1;Beta-2

----SLVKETVDRLLK----GYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTM
YFQQAWRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--DDNAVTG-
----------VTKIELPQFSIV-DYKLITKKVVFSTGSYPRLSLSFKLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFMALLEYALVNYIFF--------------------------------------
----AIDRWSRIFFPVVFSFFNIVYWLYYV--
*
>P1;Beta-3

----SFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF--------------------------------------
----AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;Epsilon

----PEASRILNTILS----NYDHKLRPGIGEKPTVVTVEISVNSLGPLSILDMEYTIDI
IFSQTWYDERLCY-NDTFESLVLNGNVVSQLWIPDTFFRNSKRTHEHEITMPNQMVRIYK
DGKVLYTIRMTIDAGCSLHMLRFPMDSHSCPLSFSSFSYPENEMIYKWEN--FKLEINEK
NSWK-----------LFQFDFT-GVSNKTEIITTPVGDFMVMTIFFNVSRRFGYVAFQNY
VPSSVTTMLSWVSFWIKTESAPARTSLGITSVLTMTTLGTFSRKNFPRVSY-ITALDFYI
AICFVFCFCALLEFAVLNFLIY--------------------------------------
----RLDNYSRVVFPVTFFFFNVLYWLVCL--
*
>P1;Delta

----ISWLPNLDGLIA----GYARNFRPGIGGPPVNVALALEVASIDHISEANMEYTMTV
FLHQSWRDSRLSY-NHTNETLGLDSRFVDKLWLPDTFIVNAKSAWFHDVTVENKLIRLQP
DGVILYSIRITSTVACDMDLAKYPMDEQECMLDLESYGYSSEDIVYYWSE-SQEH-IHGL
DKLQ-----------LAQFTITSYRFTTELMNFKSAGQFPRLSLHFHLRRNRGVYIIQSY
MPSVLLVAMSWVSFWISQAAVPARVSLGITTVLTMTTLMVSARSSLPRASA-IKALDVYF
WICYVFVFAALVEYAFAHFNAD--------------------------------------
----TIDIYARAVFPAAFAAVNVIYWAAYA--
*
>P1;Theta

----AVVQKILDRVLS----RYDVRLRPNFGGAPVPVRISIYVTSIEQISEMNMDYTITM
FFHQTWKDSRLAY-YETTLNLTLDYRMHEKLWVPDCYFLNSKDAFVHDVTVENRVFQLHP
DGTVRYGIRLTTTAACSLDLHKFPMDKQACNLVVESYGYTVEDIILFWDD-NG-NAIHMT
EE-----------LHIPQFTFL-GRTITSKEVYFYTGSYIRLILKFQVQREVNSYLVQVY
WPTVLTTITSWISFWMNYDSSAARVTIGLTSMLILTTIDSHLRDKLPNISC-IKAIDIYI
LVCLFFVFLSLLEYVYINYLFY--------------------------------------
----KVDKWSRFLFPLAFGLFNIVYWVYHM--
*
>P1;Pi

----KLSLPGFENLTA----GYNKFLRPNFGGEPVQIALTLDIASISSISESNMDYTATI
YLRQRWMDQRLVF-EGNK-SFTLDARLVEFLWVPDTYIVESKKSFLHEVTVGNRLIRLFS
NGTVLYALRITTTVACNMDLSKYPMDTQTCKLQLESWGYDGNDVEFTWLR--GNDSVRGL
EHLR-----------LAQYTIE-RYFTLVTRSQQETGNYTRLVLQFELRRNVLYFILETY
VPSTFLVVLSWVSFWISLDSVPARTCIGVTTVLSMTTLMIGSRTSLPNTNCFIKAIDVYL
GICFSFVFGALLEYAVAHYSSL--------------------------------------
----NVDHYSKLLFPLIFMLANVFYWAYYM--
*
>P1;Rho-1

-----LTKSEQLLRID----DHDFSMRPGFGGPAIPVGVDVQVESLDSISEVDMDFTMTL
YLRHYWKDERLSFPSTNNLSMTFDGRLVKKIWVPDMFFVHSKRSFIHDTTTDNVMLRVQP
DGKVLYSLRVTVTAMCNMDFSRFPLDTQTCSLEIESYAYTEDDLMLYWKK--GNDSLKTD
ERIS-----------LSQFLIQEFHTTTKLAFYSSTGWYNRLYINFTLRRHIFFFLLQTY
FPATLMVMLSWVSFWIDRRAVPARVPLGITTVLTMSTIITGVNASMPRVSY-IKAVDIYL
WVSFVFVFLSVLEYAAVNYLTT--------------------------------------
----AIDKYSRIIFPAAYILFNLIYWSIFS--
*
>P1;Rho-2

-TKIRKGKPQQLLRVD----EHDFSMRPAFGGPAIPVGVDVQVESLDSISEVDMDFTMTL
YLRHYWKDERLAFSSASNKSMTFDGRLVKKIWVPDVFFVHSKRSFTHDTTTDNIMLRVFP
DGHVLYSMRITVTAMCNMDFSHFPLDSQTCSLELESYAYTDEDLMLYWKN--GDESLKTD
EKIS-----------LSQFLIQKFHTTSRLAFYSSTGWYNRLYINFTLRRHIFFFLLQTY
FPATLMVMLSWVSFWIDRRAVPARVSLGITTVLTMTTIITGVNASMPRVSY-VKAVDIYL
WVSFVFVFLSVLEYAAVNYLTT--------------------------------------
----AIDKYSRLIFPASYIFFNLIYWSVFS--
*
>P1;Rho-3

-----PQKYEQLLHIE----DNDFAMRPGFGGSPVPVGIDVHVESIDSISETNMDFTMTF
YLRHYWKDERLSFPSTANKSMTFDHRLTRKIWVPDIFFVHSKRSFIHDTTMENIMLRVHP
DGNVLLSLRITVSAMCFMDFSRFPLDTQNCSLELESYAYNEDDLMLYWKH--GNKSLNTE
EHMS-----------LSQFFIEDFSASSGLAFYSSTGWYNRLFINFVLRRHVFFFVLQTY
FPAILMVMLSWVSFWIDRRAVPARVSLGITTVLTMSTIITAVSASMPQVSY-LKAVDVYL
WVSSLFVFLSVIEYAAVNYLTT--------------------------------------
----VIDTYSRILFPIVYILFNLFYWGVYV--
*
>P1;4COF.A_b3
TRANSPORT PROTEIN
----SFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----SQPARAA---------------------------
----AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;4COF.B_b3
TRANSPORT PROTEIN
----SFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----SQPARAA---------------------------
----AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;4COF.C_b3
TRANSPORT PROTEIN
----SFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----SQPARAA---------------------------
----AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;4COF.D_b3
TRANSPORT PROTEIN
----SFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----SQPARAA---------------------------
----AIDRWSRIVFPFTFSLFNLVYWLYYVN-
*
>P1;4COF.E_b3
TRANSPORT PROTEIN
----SFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----SQPARAA---------------------------
----AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6D6T.B_a1
TRANSPORT PROTEIN
----TVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDRLSRIAFPLLFGIFNLVYWATYL--
*
>P1;6D6T.D_a1
TRANSPORT PROTEIN
--NTTVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6D6T.A_b2
TRANSPORT PROTEIN
--NMSLVKETVDRLLK----GYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTM
YFQQAWRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--DDNAVTG-
----------VTKIELPQFSIV-DYKLITKKVVFSTGSYPRLSLSFKLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFMALLEYALVNYIFF----SQPARAA---------------------------
----AIDRWSRIFFPVVFSFFNIVYWLYYV--
*
>P1;6D6T.C_b2
TRANSPORT PROTEIN
--NMSLVKETVDRLLK----GYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTM
YFQQAWRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--DDNAVTG-
----------VTKIELPQFSIV-DYKLITKKVVFSTGSYPRLSLSFKLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFMALLEYALVNYIFF----SQPARAA---------------------------
----AIDRWSRIFFPVVFSFFNIVYWLYYV--
*
>P1;6D6T.E_g2
TRANSPORT PROTEIN
----GDVTVILNNLLE----GYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDI
FFAQTWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWN
DGRVLYTLRLTIDAECQLQLHN---DEHSCPLEFSSYGYPREEIVYQWKR----SSVEVG
D----TRSWR-----LYQFSFV-GLRNTTEVVKTTSGDYVVMSVYFDLSRRMGYFTIQTY
IPCTLIVVLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSL--------------
------------------------------------------------------------
--------------------------------
*
>P1;6HUG.A_a1
MEMBRANE PROTEIN
-DNTTVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK-----------RGYAWDGKS--KTFNSVS---------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6HUG.D_a1
MEMBRANE PROTEIN
KDNTTVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK-----------RGYAWDGK---KTFNSVS---------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6HUG.B_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----GRGPQR-------------------------TDV
N---AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6HUG.E_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----GRGPQ---------------------------DV
N---AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6HUG.C_g2
MEMBRANE PROTEIN
-----DVTVILNNLLE----GYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDI
FFAQTWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWN
DGRVLYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR----SSVEVG
D----TRSWR-----LYQFSFV-GLRNTTEVVKTTSGDYVVMSVYFDLSRRMGYFTIQTY
IPCTLIVVLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFV
SVCFIFVFSALVEYGTLHYFVS----NR--------------------------------
-RIAKMDSYARIFFPTAFCLFNLVYWVSYLYL
*
>P1;6HUJ.A_a1
MEMBRANE PROTEIN
-DNTTVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK-----------RGYAWDGKS--KTFNSVS---------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6HUJ.D_a1
MEMBRANE PROTEIN
---TTVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK-----------RGYAWDGK---KTFNSVS---------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6HUJ.B_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----GRGPQR-------------------------TDV
N---AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6HUJ.E_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----GRGPQ---------------------------DV
N---AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6HUJ.C_g2
MEMBRANE PROTEIN
-----DVTVILNNLLE----GYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDI
FFAQTWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWN
DGRVLYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR----SSVEVG
D----TRSWR-----LYQFSFV-GLRNTTEVVKTTSGDYVVMSVYFDLSRRMGYFTIQTY
IPCTLIVVLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFV
SVCFIFVFSALVEYGTLHYFVS----NR--------------------------------
-RIAKMDSYARIFFPTAFCLFNLVYWVSYLYL
*
>P1;6HUK.A_a1
MEMBRANE PROTEIN
-DNTTVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK-----------RGYAWDGKS--KTFNSVS---------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6HUK.D_a1
MEMBRANE PROTEIN
KDNTTVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK-----------RGYAWDGK---KTFNSVS---------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6HUK.B_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----GRGPQR-------------------------TDV
N---AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6HUK.E_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----GRGPQ---------------------------DV
N---AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6HUK.C_g2
MEMBRANE PROTEIN
-----DVTVILNNLLE----GYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDI
FFAQTWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWN
DGRVLYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR----SSVEVG
D----TRSWR-----LYQFSFV-GLRNTTEVVKTTSGDYVVMSVYFDLSRRMGYFTIQTY
IPCTLIVVLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFV
SVCFIFVFSALVEYGTLHYFVS----NR--------------------------------
-RIAKMDSYARIFFPTAFCLFNLVYWVSYLYL
*
>P1;6HUO.A_a1
MEMBRANE PROTEIN
----TVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK-----------RGYAWDGKS--KTFNSVS---------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6HUO.D_a1
MEMBRANE PROTEIN
----TVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK-----------RGYAWDGKS--KTFNSVS---------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6HUO.B_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----GRGPQR-------------------------TDV
N---AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6HUO.E_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----GRGPQ---------------------------DV
N---AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6HUO.C_g2
MEMBRANE PROTEIN
-----DVTVILNNLLE----GYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDI
FFAQTWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWN
DGRVLYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR----SSVEVG
D----TRSWR-----LYQFSFV-GLRNTTEVVKTTSGDYVVMSVYFDLSRRMGYFTIQTY
IPCTLIVVLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFV
SVCFIFVFSALVEYGTLHYFVS----NR--------------------------------
-RIAKMDSYARIFFPTAFCLFNLVYWVSYLYL
*
>P1;6HUP.A_a1
MEMBRANE PROTEIN
----TVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK-----------RGYAWDGKS--KTFNSVS---------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6HUP.D_a1
MEMBRANE PROTEIN
----TVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK-----------RGYAWDGK---KTFNSVS---------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6HUP.B_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----GRGPQR-------------------------TDV
N---AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6HUP.E_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----GRGPQ---------------------------DV
N---AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6HUP.C_g2
MEMBRANE PROTEIN
-----DVTVILNNLLE----GYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDI
FFAQTWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWN
DGRVLYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR----SSVEVG
D----TRSWR-----LYQFSFV-GLRNTTEVVKTTSGDYVVMSVYFDLSRRMGYFTIQTY
IPCTLIVVLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFV
SVCFIFVFSALVEYGTLHYFVS----NR--------------------------------
-RIAKMDSYARIFFPTAFCLFNLVYWVSYLYL
*
>P1;6I53.A_a1
TRANSPORT PROTEIN
-DNTTVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK-----------RGYAWDGKSVVKTFNSVS---------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6I53.D_a1
TRANSPORT PROTEIN
-DNTTVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK-----------RGYAWDGKSV-KTFNSVS---------
----KIDRLSRIAFPLLFGIFNLVYWATYLN-
*
>P1;6I53.B_b3
TRANSPORT PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----GRGPQ-----------------------PDLTDV
N---AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6I53.E_b3
TRANSPORT PROTEIN
----SFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----GRGPQ-----------------------PDLTDV
N---AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6I53.C_g2
TRANSPORT PROTEIN
------VTVILNNLLE----GYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDI
FFAQTWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWN
DGRVLYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR----SSVEVG
D----TRSWR-----LYQFSFV-GLRNTTEVVKTTSGDYVVMSVYFDLSRRMGYFTIQTY
IPCTLIVVLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFV
SVCFIFVFSALVEYGTLHYFVS----N---------------------------------
-RIAKMDSYARIFFPTAFCLFNLVYWVSYLYL
*
>P1;5O8F.A_a5/b3
MEMBRANE PROTEIN
---MSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDKMSRIVFPILFGTFNLVYWATYL--
*
>P1;5O8F.B_a5/b3
MEMBRANE PROTEIN
---MSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDKMSRIVFPILFGTFNLVYWATYL--
*
>P1;5O8F.C_a5/b3
MEMBRANE PROTEIN
---MSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDKMSRIVFPILFGTFNLVYWATYL--
*
>P1;5O8F.D_a5/b3
MEMBRANE PROTEIN
---MSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDKMSRIVFPILFGTFNLVYWATYL--
*
>P1;5O8F.E_a5/b3
MEMBRANE PROTEIN
---MSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDKMSRIVFPILFGTFNLVYWATYL--
*
>P1;5OJM.A_a5/b3
MEMBRANE PROTEIN
-----FVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDKMSRIVFPILFGTFNLVYWATYL--
*
>P1;5OJM.B_a5/b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDKMSRIVFPILFGTFNLVYWATYL--
*
>P1;5OJM.C_a5/b3
MEMBRANE PROTEIN
-----FVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDKMSRIVFPILFGTFNLVYWATYL--
*
>P1;5OJM.D_a5/b3
MEMBRANE PROTEIN
---MSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDKMSRIVFPILFGTFNLVYWATYL--
*
>P1;5OJM.E_a5/b3
MEMBRANE PROTEIN
-----FVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDKMSRIVFPILFGTFNLVYWATYL--
*
>P1;6A96.A_a5
MEMBRANE PROTEIN
--NITIFTRILDGLLD----GYDNRLRPGLGERITQVRTDIYVTSFGPVSDTEMEYTIDV
FFRQSWKDERLRF-KGPMQRLPLNNLLASKIWTPDTFFHNGKKSIAHNMTTPNKLLRLED
DGTLLYTMRLTISAECPMQLEDFPMDAHACPLKFGSYAYPNSEVVYVWTN-GSTKSVVVA
EDGSR----------LNQYHLM-GQTVGTENISTSTGEYTIMTAHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDKMSRIVFPVLFGTFNLVYWATYLNR
*
>P1;6A96.B_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----SQPARAA---------------------------
----AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6A96.E_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----SQPARAA---------------------------
----AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6A96.C_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----SQPARAA---------------------------
----AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6A96.D_b3
MEMBRANE PROTEIN
--NMSFVKETVDKLLK----GYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTM
YFQQYWRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--GDKAVTG-
----------VERIELPQFSIV-EHRLVSRNVVFATGAYPRLSLSFRLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFLALLEYAFVNYIFF----SQPARAA---------------------------
----AIDRWSRIVFPFTFSLFNLVYWLYYV--
*
>P1;6D6U.A_b2
TRANSPORT PROTEIN
--NMSLVKETVDRLLK----GYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTM
YFQQAWRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--DDNAVTG-
----------VTKIELPQFSIV-DYKLITKKVVFSTGSYPRLSLSFKLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFMALLEYALVNYIFF----SQPARAA---------------------------
----AIDRWSRIFFPVVFSFFNIVYWLYYV--
*
>P1;6D6U.C_b2
TRANSPORT PROTEIN
--NMSLVKETVDRLLK----GYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTM
YFQQAWRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG--DDNAVTG-
----------VTKIELPQFSIV-DYKLITKKVVFSTGSYPRLSLSFKLKRNIGYFILQTY
MPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYL
MGCFVFVFMALLEYALVNYIFF----SQPARAA---------------------------
----AIDRWSRIFFPVVFSFFNIVYWLYYV--
*
>P1;6D6U.B_a1
TRANSPORT PROTEIN
-DNTTVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDRLSRIAFPLLFGIFNLVYWATYL--
*
>P1;6D6U.D_a1
TRANSPORT PROTEIN
-DNTTVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVNYFTK----SQPARAA---------------------------
----KIDRLSRIAFPLLFGIFNLVYWATYLNR
*
>P1;6D6U.E_g2
TRANSPORT PROTEIN
----GDVTVILNNLLE----GYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDI
FFAQTWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWN
DGRVLYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR----SSVEVG
D----TRSWR-----LYQFSFV-GLRNTTEVVKTTSGDYVVMSVYFDLSRR----TIQTY
IPCTLIVVLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKS-----Y-VTAMDLFV
SVCFIFVFSALVEYGTLHYFVS----SQPARAA---------------------------
----KMDSYARIFFPTAFCLFNLVYWVSYL--
*
>P1;6DW0.A_a1
MEMBRANE PROTEIN
----TVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVN------------------------------------------
--------------------------------
*
>P1;6DW0.C_a1
MEMBRANE PROTEIN
----TVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTY
LPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFI
AVCYAFVFSALIEFATVN------------------------------------------
--------------------------------
*
>P1;6DW0.B_b1
MEMBRANE PROTEIN
----SYVKETVDRLLK----GYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTM
YFQQSWKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG--GEGAVTG-
----------VNKIELPQFSIV-DYKMVSKKVEFTTGAYPRLSLSFRLKRNIGYFILQTY
MPSTLITILSWVSFWINYDASAARVALGITTVLTMTTISTHLRETLPKIPY-VKAIDIYL
MGCFVFVFLALLEYAFV-------------------------------------------
-----IDKWSRMFFPITFSLFNVVYWLYYVH-
*
>P1;6DW0.E_b1
MEMBRANE PROTEIN
----SYVKETVDRLLK----GYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTM
YFQQSWKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG--GEGAVTG-
----------VNKIELPQFSIV-DYKMVSKKVEFTTGAYPRLSLSFRLKRNIGYFILQTY
MPSTLITILSWVSFWINYDASAARVALGITTVLTMTTISTHLRETLPKIPY-VKAIDIYL
MGCFVFVFLALLEYAFV-------------------------------------------
-----IDKWSRMFFPITFSLFNVVYWLYYVH-
*
>P1;6DW0.D_g2
MEMBRANE PROTEIN
----GDVTVILNNLLE----GYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDI
FFAQTWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWN
DGRVLYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR----SSVEVG
D----TRSWR-----LYQFSFV-GLRNTTEVVKTTSGDYVVMSVYFDLSRRMGYFTIQTY
IPCTLIVVLSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFV
SVCFIFVFSALVEYGTLHYFVS----N---------------------------------
--------------------------------
*
>P1;6DW1.A_a1
MEMBRANE PROTEIN
----TVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRK---------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
*
>P1;6DW1.C_a1
MEMBRANE PROTEIN
----TVFTRILDRLLD----GYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDV
FFRQSWKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITE
DGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTR-EPARSVVVA
EDGSR----------LNQYDLL-GQTVDSGIVQSSTGEYVVMTTHFHLKRK---------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
*
>P1;6DW1.B_b1
MEMBRANE PROTEIN
--NMSYVKETVDRLLK----GYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTM
YFQQSWKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG--GEGAVTG-
----------VNKIELPQFSIV-DYKMVSKKVEFTTGAYPRLSLSFRLKRN---------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
*
>P1;6DW1.E_b1
MEMBRANE PROTEIN
----SYVKETVDRLLK----GYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTM
YFQQSWKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHP
DGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG--GEGAVTG-
----------VNKIELPQFSIV-DYKMVSKKVEFTTGAYPRLSLSFRLKRN---------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
*
>P1;6DW1.D_g2
MEMBRANE PROTEIN
----GDVTVILNNLLE----GYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDI
FFAQTWYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWN
DGRVLYTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR----SSVEVG
D----TRSWR-----LYQFSFV-GLRNTTEVVKTTSGDYVVMSVYFDLSRR---------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
*
>P1;5CFB.A_gly_a3
TRANSPORT PROTEIN
-----SPSDFLDKLM-GRTSGYDARIRPNFKGPPVNVTCNIFINSFGSIAETTMDYRVNI
FLRQKWNDPRLAYSEYPDDSLDLDPSMLDSIWKPDLFFANEKGANFHEVTTDNKLLRIFK
NGNVLYSIRLTLTLSCPMDLKNFPMDVQTCIMQLESFGYTMNDLIFEWQDE---APVQVA
EG-----------LTLPQFLLKEEKDLRYCTKHYNTGKFTCIEVRFHLERQMGYYLIQMY
IPSLLIVILSWVSFWINMDAAPARVALGITTVLTMTTQSSGSRASLPKVSY-VKAIDIWM
AVCLLFVFSALLEYAAVNFVS-RAGT-------------------------KVFIDR--A
K---KIDTISRACFPLAFLIFNIFYWVIYKI-
*
>P1;5CFB.B_gly_a3
TRANSPORT PROTEIN
-----SPSDFLDKLM-GRTSGYDARIRPNFKGPPVNVTCNIFINSFGSIAETTMDYRVNI
FLRQKWNDPRLAYSEYPDDSLDLDPSMLDSIWKPDLFFANEKGANFHEVTTDNKLLRIFK
NGNVLYSIRLTLTLSCPMDLKNFPMDVQTCIMQLESFGYTMNDLIFEWQDE---APVQVA
EG-----------LTLPQFLLKEEKDLRYCTKHYNTGKFTCIEVRFHLERQMGYYLIQMY
IPSLLIVILSWVSFWINMDAAPARVALGITTVLTMTTQSSGSRASLPKVSY-VKAIDIWM
AVCLLFVFSALLEYAAVNFVS-RAGT-------------------------KVFIDR--A
K---KIDTISRACFPLAFLIFNIFYWVIYKI-
*
>P1;5CFB.C_gly_a3
TRANSPORT PROTEIN
-----SPSDFLDKLM-GRTSGYDARIRPNFKGPPVNVTCNIFINSFGSIAETTMDYRVNI
FLRQKWNDPRLAYSEYPDDSLDLDPSMLDSIWKPDLFFANEKGANFHEVTTDNKLLRIFK
NGNVLYSIRLTLTLSCPMDLKNFPMDVQTCIMQLESFGYTMNDLIFEWQDE---APVQVA
EG-----------LTLPQFLLKEEKDLRYCTKHYNTGKFTCIEVRFHLERQMGYYLIQMY
IPSLLIVILSWVSFWINMDAAPARVALGITTVLTMTTQSSGSRASLPKVSY-VKAIDIWM
AVCLLFVFSALLEYAAVNFVS-RAGT-------------------------KVFIDR--A
K---KIDTISRACFPLAFLIFNIFYWVIYKI-
*
>P1;5CFB.D_gly_a3
TRANSPORT PROTEIN
-----SPSDFLDKLM-GRTSGYDARIRPNFKGPPVNVTCNIFINSFGSIAETTMDYRVNI
FLRQKWNDPRLAYSEYPDDSLDLDPSMLDSIWKPDLFFANEKGANFHEVTTDNKLLRIFK
NGNVLYSIRLTLTLSCPMDLKNFPMDVQTCIMQLESFGYTMNDLIFEWQDE---APVQVA
EG-----------LTLPQFLLKEEKDLRYCTKHYNTGKFTCIEVRFHLERQMGYYLIQMY
IPSLLIVILSWVSFWINMDAAPARVALGITTVLTMTTQSSGSRASLPKVSY-VKAIDIWM
AVCLLFVFSALLEYAAVNFV----------------------------------IDR--A
K---KIDTISRACFPLAFLIFNIFYWVIYKI-
*
>P1;5CFB.E_gly_a3
TRANSPORT PROTEIN
-----SPSDFLDKLM-GRTSGYDARIRPNFKGPPVNVTCNIFINSFGSIAETTMDYRVNI
FLRQKWNDPRLAYSEYPDDSLDLDPSMLDSIWKPDLFFANEKGANFHEVTTDNKLLRIFK
NGNVLYSIRLTLTLSCPMDLKNFPMDVQTCIMQLESFGYTMNDLIFEWQDE---APVQVA
EG-----------LTLPQFLLKEEKDLRYCTKHYNTGKFTCIEVRFHLERQMGYYLIQMY
IPSLLIVILSWVSFWINMDAAPARVALGITTVLTMTTQSSGSRASLPKVSY-VKAIDIWM
AVCLLFVFSALLEYAAVNFVS-RAGT-------------------------KVFIDR--A
K---KIDTISRACFPLAFLIFNIFYWVIYKI-
*
