>P1;Alpha-1

---TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQS
WKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTLL
YTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AED
GS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTK------------------------------------KIDRLSRIAF
PLLFGIFNLVYWATYL---
*
>P1;Alpha-2

---TIFTRILDRLLDGYDNRLRPGLGDSITEVFTNIYVTSFGPVSDTDMEYTIDVFFRQK
WKDERLKF-KGPMNILRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRIQDDGTLL
YTMRLTVQAECPMHLEDFPMDAHSCPLKFGSYAYTTSEVTYIWTYNASDSVQV----APD
GS----RLNQYDLLGQSIGKETIKSST-GEYTVMTAHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTK------------------------------------KIDRMSRIVF
PVLFGTFNLVYWATYL---
*
>P1;Alpha-3

---TIFTRILDRLLDGYDNRLRPGLGDAVTE-KTDIYVTSFGPVSDTDMEYTIDVFFRQT
WHDERLKF-DGPMKILPLNNLLASKIWTPDTFFHNGKKSVAHNMTTPNKLLRLVDNGTLL
YTMRLTIHAECPMHLEDFPMDVHACPLKFGSYAYTTAEVVYSWTLGKNKSVEV----AQD
GS----RLNQYDLLGHVVGTEIIRSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTK------------------------------------KVDKISRIIF
PVLFAIFNLVYWATYV---
*
>P1;Alpha-5

---TIFTRILDGLLDGYDNRLRPGLGERITQVRTDIYVTSFGPVSDTEMEYTIDVFFRQS
WKDERLRF-KGPMQRLPLNNLLASKIWTPDTFFHNGKKSIAHNMTTPNKLLRLEDDGTLL
YTMRLTISAECPMQLEDFPMDAHACPLKFGSYAYPNSEVVYVWTNGSTKSVVV----AED
GS----RLNQYHLMGQTVGTENISTST-GEYTIMTAHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTK------------------------------------KIDKMSRIVF
PVLFGTFNLVYWATYL---
*
>P1;Alpha-4

---ENFTRILDSLLDGYDNRLRPGFGGPVTEVKTDIYVTSFGPVSDVEMEYTMDVFFRQT
WIDKRLKY-DGPIEILRLNNMMVTKVWTPDTFFRNGKKSVSHNMTAPNKLFRIMRNGTIL
YTMRLTISAECPMRLVDFPMDGHACPLKFGSYAYPKSEMIYTWTKGPEKSVEV----PKE
SS----SLVQYDLIGQTVSSETIKSIT-GEYIVMTVYFHLRRKMGYFMIQTYIPCIMTVI
LSQVSFWINKESVPARTVFGITTVLTMTTLSISARHSLPKVSY-ATAMDWFIAVCFAFVF
SALIEFAAVNYFTN------------------------------------KIDKYARILF
PVTFGAFNMVYWVVYL---
*
>P1;Alpha-6

---ENVSRILDNLLEGYDNRLRPGFGGAVTEVKTDIYVTSFGPVSDVEMEYTMDVFFRQT
WTDERLKF-GGPTEILSLNNLMVSKIWTPDTFFRNGKKSIAHNMTTPNKLFRIMQNGTIL
YTMRLTINADCPMRLVNFPMDGHACPLKFGSYAYPKSEIIYTWKKGPLYSVEV----PEE
SS----SLLQYDLIGQTVSSETIKSNT-GEYVIMTVYFHLQRKMGYFMIQIYTPCIMTVI
LSQVSFWINKESVPARTVFGITTVLTMTTLSISARHSLPKVSY-ATAMDWFIAVCFAFVF
SALIEFAAVNYFTN------------------------------------KIDQYSRILF
PVAFAGFNLVYWVVYL---
*
>P1;Gamma-1

---GDITQILNSLLQGYDNKLRPDIGVRPTVIETDVYVNSIGPVDPINMEYTIDIIFAQT
WFDSRLKF-NSTMKVLMLNSNMVGKIWIPDTFFRNSRKSDAHWITTPNRLLRIWNDGRVL
YTLRLTINAECYLQLHNFPMDEHSCPLEFSSYGYPKNEIEYKWKK---PSVEV----AD-
--PKYWRLYQFAFVGLRNSTEITHTIS-GDYVIMTIFFDLSRRMGYFTIQTYIPCILTVV
LSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFVF
AALMEYGTLHYFTS------------------------------------KIDSYSRIFF
PTAFALFNLVYWVGYL---
*
>P1;Gamma-2

---GDVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQT
WYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRVL
YTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD-
--TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIVV
LSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFVF
SALVEYGTLHYFVS------------------------------------KMDSYARIFF
PTAFCLFNLVYWVSYL---
*
>P1;Gamma-3

---TDVTLILNKLLREYDKKLRPDIGIKPTVIDVDIYVNSIGPVSSINMEYQIDIFFAQT
WTDSRLRF-NSTMKILTLNSNMVGLIWIPDTIFRNSKTAEAHWITTPNQLLRIWNDGKIL
YTLRLTINAECQLQLHNFPMDEHSCPLIFSSYGYPKEEMIYRWRK---NSVEA----AD-
--QKSWRLYQFDFMGLRNTTEIVTTSA-GDYVVMTIYFELSRRMGYFTIQTYIPCILTVV
LSWVSFWIKKDATPARTALGITTVLTMTTLSTIARKSLPRVSY-VTAMDLFVTVCFLFVF
AALMEYATLNYYSS------------------------------------ELDSYSRVFF
PTSFLLFNLVYWVGYL---
*
>P1;Beta-1

---SYVKETVDRLLKGYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTMYFQQS
WKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG-GEGAVTGVNKI---
------ELPQFSIVDYKMVSKKVEFTT-GAYPRLSLSFRLKRNIGYFILQTYMPSTLITI
LSWVSFWINYDASAARVALGITTVLTMTTISTHLRETLPKIPY-VKAIDIYLMGCFVFVF
LALLEYAFVNYIFF------------------------------------SIDKWSRMFF
PITFSLFNVVYWLYYV---
*
>P1;Beta-2

---SLVKETVDRLLKGYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTMYFQQA
WRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-DDNAVTGVTKI---
------ELPQFSIVDYKLITKKVVFST-GSYPRLSLSFKLKRNIGYFILQTYMPSILITI
LSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFVF
MALLEYALVNYIFF------------------------------------AIDRWSRIFF
PVVFSFFNIVYWLYYV---
*
>P1;Beta-3

---SFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQY
WRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI---
------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILITI
LSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFVF
LALLEYAFVNYIFF------------------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;Epsilon

---PEASRILNTILSNYDHKLRPGIGEKPTVVTVEISVNSLGPLSILDMEYTIDIIFSQT
WYDERLCY-NDTFESLVLNGNVVSQLWIPDTFFRNSKRTHEHEITMPNQMVRIYKDGKVL
YTIRMTIDAGCSLHMLRFPMDSHSCPLSFSSFSYPENEMIYKWEN-FKLEINEKNSW---
------KLFQFDFTGVSNKTEIITTPV-GDFMVMTIFFNVSRRFGYVAFQNYVPSSVTTM
LSWVSFWIKTESAPARTSLGITSVLTMTTLGTFSRKNFPRVSY-ITALDFYIAICFVFCF
CALLEFAVLNFLIY------------------------------------RLDNYSRVVF
PVTFFFFNVLYWLVCL---
*
>P1;Delta

---ISWLPNLDGLIAGYARNFRPGIGGPPVNVALALEVASIDHISEANMEYTMTVFLHQS
WRDSRLSY-NHTNETLGLDSRFVDKLWLPDTFIVNAKSAWFHDVTVENKLIRLQPDGVIL
YSIRITSTVACDMDLAKYPMDEQECMLDLESYGYSSEDIVYYWSESQEH-IHGLDKL---
------QLAQFTITSYRFTTELMNFKSAGQFPRLSLHFHLRRNRGVYIIQSYMPSVLLVA
MSWVSFWISQAAVPARVSLGITTVLTMTTLMVSARSSLPRASA-IKALDVYFWICYVFVF
AALVEYAFAHFNAD------------------------------------TIDIYARAVF
PAAFAAVNVIYWAAYA---
*
>P1;Theta

---AVVQKILDRVLSRYDVRLRPNFGGAPVPVRISIYVTSIEQISEMNMDYTITMFFHQT
WKDSRLAY-YETTLNLTLDYRMHEKLWVPDCYFLNSKDAFVHDVTVENRVFQLHPDGTVR
YGIRLTTTAACSLDLHKFPMDKQACNLVVESYGYTVEDIILFWDDNG-NAIHMTEEL---
------HIPQFTFLGRTITSKEVYFYT-GSYIRLILKFQVQREVNSYLVQVYWPTVLTTI
TSWISFWMNYDSSAARVTIGLTSMLILTTIDSHLRDKLPNISC-IKAIDIYILVCLFFVF
LSLLEYVYINYLFY------------------------------------KVDKWSRFLF
PLAFGLFNIVYWVYHM---
*
>P1;Pi

---KLSLPGFENLTAGYNKFLRPNFGGEPVQIALTLDIASISSISESNMDYTATIYLRQR
WMDQRLVF-EGNK-SFTLDARLVEFLWVPDTYIVESKKSFLHEVTVGNRLIRLFSNGTVL
YALRITTTVACNMDLSKYPMDTQTCKLQLESWGYDGNDVEFTWLR-GNDSVRGLEHL---
------RLAQYTIERYFTLVTRSQQET-GNYTRLVLQFELRRNVLYFILETYVPSTFLVV
LSWVSFWISLDSVPARTCIGVTTVLSMTTLMIGSRTSLPNTNCFIKAIDVYLGICFSFVF
GALLEYAVAHYSSL------------------------------------NVDHYSKLLF
PLIFMLANVFYWAYYM---
*
>P1;Rho-1

----LTKSEQLLRIDDHDFSMRPGFGGPAIPVGVDVQVESLDSISEVDMDFTMTLYLRHY
WKDERLSFPSTNNLSMTFDGRLVKKIWVPDMFFVHSKRSFIHDTTTDNVMLRVQPDGKVL
YSLRVTVTAMCNMDFSRFPLDTQTCSLEIESYAYTEDDLMLYWKK-GNDSLKTDERI---
------SLSQFLIQEFHTTTKLAFYSSTGWYNRLYINFTLRRHIFFFLLQTYFPATLMVM
LSWVSFWIDRRAVPARVPLGITTVLTMSTIITGVNASMPRVSY-IKAVDIYLWVSFVFVF
LSVLEYAAVNYLTT------------------------------------AIDKYSRIIF
PAAYILFNLIYWSIFS---
*
>P1;Rho-2

TKIRKGKPQQLLRVDEHDFSMRPAFGGPAIPVGVDVQVESLDSISEVDMDFTMTLYLRHY
WKDERLAFSSASNKSMTFDGRLVKKIWVPDVFFVHSKRSFTHDTTTDNIMLRVFPDGHVL
YSMRITVTAMCNMDFSHFPLDSQTCSLELESYAYTDEDLMLYWKN-GDESLKTDEKI---
------SLSQFLIQKFHTTSRLAFYSSTGWYNRLYINFTLRRHIFFFLLQTYFPATLMVM
LSWVSFWIDRRAVPARVSLGITTVLTMTTIITGVNASMPRVSY-VKAVDIYLWVSFVFVF
LSVLEYAAVNYLTT------------------------------------AIDKYSRLIF
PASYIFFNLIYWSVFS---
*
>P1;Rho-3

----PQKYEQLLHIEDNDFAMRPGFGGSPVPVGIDVHVESIDSISETNMDFTMTFYLRHY
WKDERLSFPSTANKSMTFDHRLTRKIWVPDIFFVHSKRSFIHDTTMENIMLRVHPDGNVL
LSLRITVSAMCFMDFSRFPLDTQNCSLELESYAYNEDDLMLYWKH-GNKSLNTEEHM---
------SLSQFFIEDFSASSGLAFYSSTGWYNRLFINFVLRRHVFFFVLQTYFPAILMVM
LSWVSFWIDRRAVPARVSLGITTVLTMSTIITAVSASMPQVSY-LKAVDVYLWVSSLFVF
LSVIEYAAVNYLTT------------------------------------VIDTYSRILF
PIVYILFNLFYWGVYV---
*
>P1;4COF.B_b3
TRANSPORT PROTEIN
---SFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQY
WRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI---
------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILITI
LSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFVF
LALLEYAFVNYIFFSQPARAA-----------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6D6T.B_a1
TRANSPORT PROTEIN
---TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQS
WKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTLL
YTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AED
GS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTKSQPARAA-----------------------------KIDRLSRIAF
PLLFGIFNLVYWATYL---
*
>P1;6D6T.A_b2
TRANSPORT PROTEIN
-NMSLVKETVDRLLKGYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTMYFQQA
WRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-DDNAVTGVTKI---
------ELPQFSIVDYKLITKKVVFST-GSYPRLSLSFKLKRNIGYFILQTYMPSILITI
LSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFVF
MALLEYALVNYIFFSQPARAA-----------------------------AIDRWSRIFF
PVVFSFFNIVYWLYYV---
*
>P1;6D6T.E_g2
TRANSPORT PROTEIN
---GDVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQT
WYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRVL
YTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD-
--TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIVV
LSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSL----------------------
------------------------------------------------------------
-------------------
*
>P1;6HUG.A_a1
MEMBRANE PROTEIN
---TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQS
WKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTLL
YTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AED
GS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTK-------RGYAWDGKSKTFNSVS-------------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUG.B_b3
MEMBRANE PROTEIN
-NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQY
WRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI---
------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILITI
LSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFVF
LALLEYAFVNYIFFGRGPQR--------------------TDVN------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUG.C_g2
MEMBRANE PROTEIN
----DVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQT
WYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRVL
YTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD-
--TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIVV
LSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFVF
SALVEYGTLHYFVSNR----------------------------RIA---KMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
>P1;6HUJ.A_a1
MEMBRANE PROTEIN
---TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQS
WKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTLL
YTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AED
GS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTK-------RGYAWDGKSKTFNSVS-------------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUJ.B_b3
MEMBRANE PROTEIN
-NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQY
WRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI---
------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILITI
LSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFVF
LALLEYAFVNYIFFGRGPQR--------------------TDVN------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUJ.C_g2
MEMBRANE PROTEIN
----DVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQT
WYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRVL
YTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD-
--TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIVV
LSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFVF
SALVEYGTLHYFVSNR----------------------------RIA---KMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
>P1;6HUK.A_a1
MEMBRANE PROTEIN
---TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQS
WKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTLL
YTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AED
GS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTK-------RGYAWDGKSKTFNSVS-------------KIDRLSRIAF
PLLFGIFNLVYWATYLN--
*
>P1;6HUK.B_b3
MEMBRANE PROTEIN
-NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQY
WRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI---
------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILITI
LSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFVF
LALLEYAFVNYIFFGRGPQR--------------------TDVN------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUK.C_g2
MEMBRANE PROTEIN
----DVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQT
WYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRVL
YTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD-
--TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIVV
LSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFVF
SALVEYGTLHYFVSNR----------------------------RIA---KMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
>P1;6HUO.A_a1
MEMBRANE PROTEIN
---TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQS
WKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTLL
YTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AED
GS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTK-------RGYAWDGKSKTFNSVS-------------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUO.B_b3
MEMBRANE PROTEIN
-NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQY
WRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI---
------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILITI
LSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFVF
LALLEYAFVNYIFFGRGPQR--------------------TDVN------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUO.C_g2
MEMBRANE PROTEIN
----DVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQT
WYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRVL
YTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD-
--TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIVV
LSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFVF
SALVEYGTLHYFVSNR----------------------------RIA---KMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
>P1;6HUP.A_a1
MEMBRANE PROTEIN
---TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQS
WKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTLL
YTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AED
GS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTK-------RGYAWDGKSKTFNSVS-------------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6HUP.B_b3
MEMBRANE PROTEIN
-NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQY
WRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI---
------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILITI
LSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFVF
LALLEYAFVNYIFFGRGPQR--------------------TDVN------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6HUP.C_g2
MEMBRANE PROTEIN
----DVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQT
WYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRVL
YTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD-
--TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIVV
LSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFVF
SALVEYGTLHYFVSNR----------------------------RIA----KMDSYARIF
FPTAFCLFNLVYWVSYLYL
*
>P1;6I53.A_a1
TRANSPORT PROTEIN
---TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQS
WKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTLL
YTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AED
GS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTK-------RGYAWDGKSKTFNSVS-------------KIDRLSRIAF
PLLFGIFNLVYWATYLNR-
*
>P1;6I53.B_b3
TRANSPORT PROTEIN
-NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQY
WRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI---
------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILITI
LSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFVF
LALLEYAFVNYIFFGRGPQ------------------PDLTDVN------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6I53.C_g2
TRANSPORT PROTEIN
-----VTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQT
WYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRVL
YTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD-
--TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIVV
LSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFVF
SALVEYGTLHYFVSN-----------------------------RIA---KMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
>P1;5O8F.A_a5/b3
MEMBRANE PROTEIN
--MSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQY
WRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI---
------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTKSQPARAA-----------------------------KIDKMSRIVF
PILFGTFNLVYWATYL---
*
>P1;5OJM.A_a5/b3
MEMBRANE PROTEIN
----FVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQY
WRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI---
------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTKSQPARAA-----------------------------KIDKMSRIVF
PILFGTFNLVYWATYL---
*
>P1;6A96.A_a5
MEMBRANE PROTEIN
---TIFTRILDGLLDGYDNRLRPGLGERITQVRTDIYVTSFGPVSDTEMEYTIDVFFRQS
WKDERLRF-KGPMQRLPLNNLLASKIWTPDTFFHNGKKSIAHNMTTPNKLLRLEDDGTLL
YTMRLTISAECPMQLEDFPMDAHACPLKFGSYAYPNSEVVYVWTNGSTKSVVV----AED
GS----RLNQYHLMGQTVGTENISTST-GEYTIMTAHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTKSQPARAA-----------------------------KIDKMSRIVF
PVLFGTFNLVYWATYLN--
*
>P1;6A96.B_b3
MEMBRANE PROTEIN
-NMSFVKETVDKLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQY
WRDKRLAY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-GDKAVTGVERI---
------ELPQFSIVEHRLVSRNVVFAT-GAYPRLSLSFRLKRNIGYFILQTYMPSILITI
LSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFVF
LALLEYAFVNYIFFSQPARAA-----------------------------AIDRWSRIVF
PFTFSLFNLVYWLYYV---
*
>P1;6D6U.A_b2
TRANSPORT PROTEIN
-NMSLVKETVDRLLKGYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTMYFQQA
WRDKRLSY-NVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRG-DDNAVTGVTKI---
------ELPQFSIVDYKLITKKVVFST-GSYPRLSLSFKLKRNIGYFILQTYMPSILITI
LSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPY-VKAIDMYLMGCFVFVF
MALLEYALVNYIFFSQPARAA-----------------------------AIDRWSRIFF
PVVFSFFNIVYWLYYV---
*
>P1;6D6U.B_a1
TRANSPORT PROTEIN
---TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQS
WKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTLL
YTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AED
GS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTKSQPARAA-----------------------------KIDRLSRIAF
PLLFGIFNLVYWATYL---
*
>P1;6D6U.E_g2
TRANSPORT PROTEIN
---GDVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQT
WYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRVL
YTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD-
--TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRM---TIQTYIPCTLIVV
LSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKS-----Y-VTAMDLFVSVCFIFVF
SALVEYGTLHYFVSSQPARAA-----------------------------KMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
>P1;6DW0.A_a1
MEMBRANE PROTEIN
---TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQS
WKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTLL
YTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AED
GS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVN--------------------------------------------------
-------------------
*
>P1;6DW0.B_b1
MEMBRANE PROTEIN
---SYVKETVDRLLKGYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTMYFQQS
WKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG-GEGAVTGVNKI---
------ELPQFSIVDYKMVSKKVEFTT-GAYPRLSLSFRLKRNIGYFILQTYMPSTLITI
LSWVSFWINYDASAARVALGITTVLTMTTISTHLRETLPKIPY-VKAIDIYLMGCFVFVF
LALLEYAFV------------------------------------------IDKWSRMFF
PITFSLFNVVYWLYYVH--
*
>P1;6DW0.D_g2
MEMBRANE PROTEIN
---GDVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQT
WYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRVL
YTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD-
--TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIVV
LSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFVF
SALVEYGTLHYFVSN---------------------------------------------
-------------------
*
>P1;6DW1.A_a1
MEMBRANE PROTEIN
---TVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQS
WKDERLKF-KGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTLL
YTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYEWTREPARSVVV----AED
GS----RLNQYDLLGQTVDSGIVQSST-GEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVI
LSQVSFWLNRESVPARTVFGVTTVLTMTTLSISARNSLPKVAY-ATAMDWFIAVCYAFVF
SALIEFATVNYFTKRGTKKTFN-------------------------SVSKIDRLSRIAF
PLLFGIFNLVYWATYL---
*
>P1;6DW1.B_b1
MEMBRANE PROTEIN
-NMSYVKETVDRLLKGYDIRLRPDFGGPPVDVGMRIDVASIDMVSEVNMDYTLTMYFQQS
WKDKRLSY-SGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVL
YGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWNG-GEGAVTGVNKI---
------ELPQFSIVDYKMVSKKVEFTT-GAYPRLSLSFRLKRNIGYFILQTYMPSTLITI
LSWVSFWINYDASAARVALGITTVLTMTTISTHLRETLPKIPY-VKAIDIYLMGCFVFVF
LALLEYAFVNYIFF-------------------------------------IDKWSRMFF
PITFSLFNVVYWLYYVH--
*
>P1;6DW1.D_g2
MEMBRANE PROTEIN
---GDVTVILNNLLEGYDNKLRPDIGVKPTLIHTDMYVNSIGPVNAINMEYTIDIFFAQT
WYDRRLKF-NSTIKVLRLNSNMVGKIWIPDTFFRNSKKADAHWITTPNRMLRIWNDGRVL
YTLRLTIDAECQLQLHNFPMDEHSCPLEFSSYGYPREEIVYQWKR---SSVEV----GD-
--TRSWRLYQFSFVGLRNTTEVVKTTS-GDYVVMSVYFDLSRRMGYFTIQTYIPCTLIVV
LSWVSFWINKDAVPARTSLGITTVLTMTTLSTIARKSLPKVSY-VTAMDLFVSVCFIFVF
SALVEYGTLHYFVSNR----------------------------RIA---KMDSYARIFF
PTAFCLFNLVYWVSYLYL-
*
